#!/bin/bash
#SBATCH -p short # Partition to submit to
#SBATCH -n 1 # Number of cores requested
#SBATCH -N 1 # Ensure that all cores are on one machine
#SBATCH -t 720 # Runtime in minutes
#SBATCH --mem=60000 # Memory per cpu in MB (see also --mem-per-cpu)
#SBATCH -o hostname_%A_%a.out # Standard out goes to this file
#SBATCH -e hostname_%A_%a.err # Standard err goes to this filehostname
date
/data/user/abgvg9/rosetta_LDS_time_profiling/source/bin/ligand_discovery_search_protocol.linuxgccrelease @100_lig_args
date
