#!/bin/bash
#SBATCH -p short # Partition to submit to\n")
#SBATCH -n 1 # Number of cores requested\n")
#SBATCH -N 1 # Ensure that all cores are on one machine\n")
#SBATCH -t 720 # Runtime in minutes\n")
#SBATCH --mem=1280 # Memory per cpu in MB (see also --mem-per-cpu)\n")
#SBATCH -o /scratch/abgvg9/motif_library_work/789_new/7byu/7byu_hostname_%A_%a.out # Standard out goes to this file\n")
#SBATCH -e /scratch/abgvg9/motif_library_work/789_new/7byu/7byu_hostname_%A_%a.err # Standard err goes to this filehostname\n")
cd /scratch/abgvg9/motif_library_work/789_new/7byu
mkdir /scratch/abgvg9/motif_library_work/789_new/7byu/Ligand_motif_dir
/data/project/thymelab/running_Rosetta/ari_work/Rosetta_Code/main/source/bin/ligand_motifs.linuxgccrelease @/scratch/abgvg9/motif_library_work/789_new/7byu/7byu_1PG_flags
mv Ligand_motif_dir 7byu_1PG
mv AllMattMotifsFile.motifs 7byu_1PG
mkdir /scratch/abgvg9/motif_library_work/789_new/7byu/Ligand_motif_dir
/data/project/thymelab/running_Rosetta/ari_work/Rosetta_Code/main/source/bin/ligand_motifs.linuxgccrelease @/scratch/abgvg9/motif_library_work/789_new/7byu/7byu_EDO_flags
mv Ligand_motif_dir 7byu_EDO
mv AllMattMotifsFile.motifs 7byu_EDO
